version: '3.8'
services:
  web:
    build:
      context: .
      target: 'prod'
      dockerfile: './docker/app/Dockerfile'
    ports:
      - 8000:8000
      - 5678:5678
    container_name: house-notes-be
    environment:
      DATABASE_URL: ${DATABASE_URL}
      FLASK_APP: "app.py"
      APP_SETTINGS: ${APP_SETTINGS}
      PYTHONPATH: "./app"
      PYTHONUNBUFFERED: "1"
      JWT_SECRET_KEY: ${JWT_SECRET_KEY}
      USER_TEST: ${USER_TEST}
      PASS_TEST: ${PASS_TEST}
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports