version: '3.8'
services:
  web:
    build:
      context: .
      target: 'prod'
      dockerfile: './docker/app/Dockerfile'
    ports:
      - 8000:8000
      - 5678:5678
    volumes:
      - ./logs:/app/logs
      - ./reports:/app/reports