apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-notes-be
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  ingressClassName: nginx
  rules:
  - host: house.jx567.net
    http:
      paths:
      - backend:
          service:
            name: house-notes-be
            port:
              number: 8000
        path: /
        pathType: Prefix
