apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: house-notes-be
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
spec:
  rules:
    - host: house.jx567.net
      http:
        paths:
          - path: /(.*)
            pathType: Prefix
            backend:
              service:
                name: house-notes-be
                port:
                  name: http
